In [1]:
import numpy as np

### Q1

In [2]:
x = np.array([[1, -2, 2, 1]]).astype(np.float64)
# w1 = np.array([[(2/5), (-1/5), (2/5)],
#                [(-1/5), (1/5), (-1/5)],
#                [(1/5), (-1/5), (1/5)],
#                [(-2/5), (1/5), (-2/5)]])
w1 = (1/5) * np.array([[2, -1, 2],
               [-1, 1, -1],
               [1, -1, 1],
               [-2, 1, -2]]).astype(np.float64)
w2 = (2/5) * np.array([[-1, 1],
                       [1, -1],
                       [-1, 1]]).astype(np.float64)

def lelu(x):
    return np.max(x[0], 0.999 * x[0])

b1 =  np.full((1, 3), 0.5).astype(np.float64)
b2 =  np.full((1, 2), 0.5).astype(np.float64)
b3 =  np.full((1, 3), 0.5).astype(np.float64)
b4 =  np.full((1, 4), 0.5).astype(np.float64)
inp_enc = x @ w1
print(inp_enc)
inp_enc = inp_enc + b1
print(inp_enc)
# inp_enc = np.apply_along_axis(lelu, 0, inp_enc)
# print(inp_enc)

enc_lat = inp_enc @ w2
print(enc_lat)
enc_lat = enc_lat + b2
print(enc_lat)

lat_dec = enc_lat @ w2.T
print(lat_dec)
lat_dec = lat_dec + b3
print(lat_dec)

dec_out = lat_dec @ w1.T
print(dec_out)
dec_out = dec_out + b4
print(dec_out)

[[ 0.8 -0.8  0.8]]
[[ 1.3 -0.3  1.3]]
[[-1.16  1.16]]
[[-0.66  1.66]]
[[ 0.928 -0.928  0.928]]
[[ 1.428 -0.428  1.428]]
[[ 1.228  -0.6568  0.6568 -1.228 ]]
[[ 1.728  -0.1568  1.1568 -0.728 ]]


In [3]:
code_inp = np.array([[1, 1]])
lat_dec = code_inp @ w2.T
print(lat_dec)
lat_dec = lat_dec + b3
print(lat_dec)

dec_out = lat_dec @ w1.T
print(dec_out)
dec_out = dec_out + b4
print(dec_out)

[[0. 0. 0.]]
[[0.5 0.5 0.5]]
[[ 0.3 -0.1  0.1 -0.3]]
[[0.8 0.4 0.6 0.2]]
