In [8]:
import numpy as np

### Q1

In [9]:
x = np.array([[1, -2, 2, 1]]).astype(np.float64)
# w1 = np.array([[(2/5), (-1/5), (2/5)],
#                [(-1/5), (1/5), (-1/5)],
#                [(1/5), (-1/5), (1/5)],
#                [(-2/5), (1/5), (-2/5)]])
w1 = (1/5) * np.array([[2, -1, 2],
               [-1, 1, -1],
               [1, -1, 1],
               [-2, 1, -2]]).astype(np.float64)
w2 = (1/2) * np.array([[-1, 1],
                       [1, -1],
                       [-1, 1]]).astype(np.float64)

def lelu(x):
    return np.max(x[0], 0.999 * x[0])

b1 =  np.full((1, 3), 0.5).astype(np.float64)
b2 =  np.full((1, 2), 0.5).astype(np.float64)
b3 =  np.full((1, 3), 0.5).astype(np.float64)
b4 =  np.full((1, 4), 0.5).astype(np.float64)
inp_enc = x @ w1
print(inp_enc)
inp_enc = inp_enc + b1
print(inp_enc)
# inp_enc = np.apply_along_axis(lelu, 0, inp_enc)
# print(inp_enc)

enc_lat = inp_enc @ w2
print(enc_lat)
enc_lat = enc_lat + b2
print(enc_lat)

lat_dec = enc_lat @ w2.T
print(lat_dec)
lat_dec = lat_dec + b3
print(lat_dec)

dec_out = lat_dec @ w1.T
print(dec_out)
dec_out = dec_out + b4
print(dec_out)

[[ 0.8 -0.8  0.8]]
[[ 1.3 -0.3  1.3]]
[[-1.45  1.45]]
[[-0.95  1.95]]
[[ 1.45 -1.45  1.45]]
[[ 1.95 -0.95  1.95]]
[[ 1.75 -0.97  0.97 -1.75]]
[[ 2.25 -0.47  1.47 -1.25]]


In [10]:
code_inp = np.array([[1, 1]])
lat_dec = code_inp @ w2.T
print(lat_dec)
lat_dec = lat_dec + b3
print(lat_dec)

dec_out = lat_dec @ w1.T
print(dec_out)
dec_out = dec_out + b4
print(dec_out)

[[0. 0. 0.]]
[[0.5 0.5 0.5]]
[[ 0.3 -0.1  0.1 -0.3]]
[[0.8 0.4 0.6 0.2]]


### Q4

In [11]:
print(w2.T)

[[-0.5  0.5 -0.5]
 [ 0.5 -0.5  0.5]]


In [12]:
code_inp = np.array([[-1, 1]])
lat_dec = code_inp @ w2.T
print(lat_dec)
lat_dec = lat_dec + b3
print(lat_dec)

dec_out = lat_dec @ w1.T
print(dec_out)
dec_out = dec_out + b4
print(dec_out)

[[ 1. -1.  1.]]
[[ 1.5 -0.5  1.5]]
[[ 1.3 -0.7  0.7 -1.3]]
[[ 1.8 -0.2  1.2 -0.8]]
