In [1]:
import numpy as np
from activation_func import activation_func

### MLP

In [2]:
from MLP import MLP

X = np.array([[0.25, 0.5, 0.75], [0.75, 0.5, 0.25]])
y = np.array([[0.25], [0.75]])
input_size = X.shape[1]
hidden_size = 2
output_size = y.shape[1]
V = np.full((input_size, hidden_size), 0.5)
W = np.full((hidden_size, output_size), 0.5)

hidden_act = activation_func.bipolar_sigmoid
de_hidden_act = activation_func.d_bipolar_sigmoid
output_act = activation_func.bipolar_sigmoid
de_output_act = activation_func.d_bipolar_sigmoid
mlp = MLP(
    input_size,
    hidden_size,
    output_size,
    activation_func_hidden=hidden_act,
    activation_func_output=output_act,
    derivative_act_hidden=de_hidden_act,
    derivative_act_output=de_output_act,
    batch_mode=True,
    bias=False,
    print_steps=True,
    decimal_point=3,
    init_weights=(V, W)
)
v,w = mlp.train(X, y, epochs=1, learning_rate=1.0)

(3, 2)
epoch 1
x                   z_in           z                y_in     y
------------------  -------------  -------------  ------  ----
[[0.25 0.5  0.75]]  [[0.75 0.75]]  [[0.36 0.36]]    0.36  0.36
[[0.75 0.5  0.25]]  [[0.75 0.75]]  [[0.36 0.36]]    0.36  0.36
δ_H                δ_O  h(q)             o(q)
---------------  -----  ---------------  ---------
[[-0.01 -0.01]]  -0.04  [[-0.   -0.  ]   [[-0.01]
                         [-0.   -0.  ]    [-0.01]]
                         [-0.01 -0.01]]
[[-0.06 -0.06]]  -0.28  [[-0.05 -0.05]   [[-0.1]
                         [-0.03 -0.03]    [-0.1]]
                         [-0.02 -0.02]]
o = [[-0.11]
 [-0.11]]
h = [[-0.05 -0.05]
 [-0.03 -0.03]
 [-0.02 -0.02]]
Δv = [[0.02 0.02]
 [0.02 0.02]
 [0.01 0.01]]
Δw = [[0.06]
 [0.06]]
v = [[0.52 0.52]
 [0.52 0.52]
 [0.51 0.51]]
w = [[0.56]
 [0.56]]
(3, 2)
epoch 1
x                   z_in           z                  y_in      y
------------------  -------------  ---------------  ------  -----
[[0.

In [3]:
from MLP import MLP

input_size = 3
hidden_size = 2
output_size = 2
X = np.array([[1, 1, 1], [1, -1, -1]])
y = np.array([[1, 1], [-1, -1]])

V = np.array([
    [0.22, 0.57],
    [0.7, 0.21],
    [0.18, 0.11],
    [0.38, 0.44]
])

W = np.array([
    [0.09, 0.81],
    [0.77, 0.86],
    [0.17, 0.29]
])

hidden_act = activation_func.bipolar_sigmoid
de_hidden_act = activation_func.d_bipolar_sigmoid
output_act = activation_func.bipolar_sigmoid
de_output_act = activation_func.d_bipolar_sigmoid
mlp = MLP(
    input_size,
    hidden_size,
    output_size,
    activation_func_hidden=hidden_act,
    activation_func_output=output_act,
    derivative_act_hidden=de_hidden_act,
    derivative_act_output=de_output_act,
    batch_mode=False,
    bias=True,
    print_steps=True,
    init_weights=(V, W)
)
v, w = mlp.train(X, y, epochs=1, learning_rate=0.2)

(4, 2)
epoch 1
(3, 2)


ValueError: operands could not be broadcast together with shapes (4,2) (3,2) (4,2) 