In [1]:
import numpy as np
from activation_func import activation_func

## MLP

In [13]:
from MLP import MLP

### 2022 Example

In [7]:
X = np.array([[0.25, 0.5, 0.75], [0.75, 0.5, 0.25]])
y = np.array([[0.25], [0.75]])
input_size = X.shape[1]
hidden_size = 2
output_size = y.shape[1]
V = np.full((input_size, hidden_size), 0.5)
W = np.full((hidden_size, output_size), 0.5)

hidden_act = activation_func.bipolar_sigmoid
de_hidden_act = activation_func.d_bipolar_sigmoid
output_act = activation_func.identity
de_output_act = activation_func.d_identity
mlp = MLP(
    input_size,
    hidden_size,
    output_size,
    activation_func_hidden=hidden_act,
    activation_func_output=output_act,
    derivative_act_hidden=de_hidden_act,
    derivative_act_output=de_output_act,
    batch_mode=True,
    bias=False,
    print_steps=True,
    decimal_point=3,
    init_weights=(V, W)
)
v,w = mlp.train(X, y, epochs=1, learning_rate=1.0)

epoch 1
[[0.25 0.5  0.75]]
[[0.75 0.5  0.25]]
x                   z_in           z                  y_in      y
------------------  -------------  ---------------  ------  -----
[[0.25 0.5  0.75]]  [[0.75 0.75]]  [[0.358 0.358]]   0.358  0.358
[[0.75 0.5  0.25]]  [[0.75 0.75]]  [[0.358 0.358]]   0.358  0.358
δ_H                   δ_O  h(q)               o(q)
-----------------  ------  -----------------  ---------
[[0.024 0.024]]     0.108  [[0.006 0.006]     [[0.039]
                            [0.012 0.012]      [0.039]]
                            [0.018 0.018]]
[[-0.085 -0.085]]  -0.392  [[-0.064 -0.064]   [[-0.14]
                            [-0.043 -0.043]    [-0.14]]
                            [-0.021 -0.021]]
o = [[-0.102]
 [-0.102]]
h = [[-0.058 -0.058]
 [-0.031 -0.031]
 [-0.004 -0.004]]
Δv = [[0.029 0.029]
 [0.015 0.015]
 [0.002 0.002]]
Δw = [[0.051]
 [0.051]]
v = [[0.529 0.529]
 [0.515 0.515]
 [0.502 0.502]]
w = [[0.551]
 [0.551]]


### 2021 Example

In [12]:
X = np.array([[0.25, 0.5, 0.25], [0.5, 0.25, 0.5]])
y = np.array([[0.5], [0.75]])
input_size = X.shape[1]
hidden_size = 2
output_size = y.shape[1]
V = np.full((input_size, hidden_size), 0.5)
W = np.full((hidden_size, output_size), 0.5)

hidden_act = activation_func.bipolar_sigmoid
de_hidden_act = activation_func.d_bipolar_sigmoid
output_act = activation_func.identity
de_output_act = activation_func.d_identity
mlp = MLP(
    input_size,
    hidden_size,
    output_size,
    activation_func_hidden=hidden_act,
    activation_func_output=output_act,
    derivative_act_hidden=de_hidden_act,
    derivative_act_output=de_output_act,
    batch_mode=False,
    bias=False,
    print_steps=True,
    decimal_point=3,
    init_weights=(V, W)
)
v,w = mlp.train(X, y, epochs=1, learning_rate=1.0)

epoch 1
[[0.25 0.5  0.25]]
[[0.5  0.25 0.5 ]]
x                   z_in             z                  y_in      y
------------------  ---------------  ---------------  ------  -----
[[0.25 0.5  0.25]]  [[0.5 0.5]]      [[0.245 0.245]]   0.245  0.245
[[0.5  0.25 0.5 ]]  [[0.647 0.647]]  [[0.313 0.313]]   0.352  0.352
δ_H                   δ_O  Δv               Δw         v                w
-----------------  ------  ---------------  ---------  ---------------  ---------
[[-0.06 -0.06]]    -0.255  [[0.015 0.015]   [[0.062]   [[0.515 0.515]   [[0.562]
                            [0.03  0.03 ]    [0.062]]   [0.53  0.53 ]    [0.562]]
                            [0.015 0.015]]              [0.515 0.515]]
[[-0.101 -0.101]]  -0.398  [[0.05  0.05 ]   [[0.125]   [[0.565 0.565]   [[0.687]
                            [0.025 0.025]    [0.125]]   [0.555 0.555]    [0.687]]
                            [0.05  0.05 ]]              [0.565 0.565]]


In [5]:
input_size = 3
hidden_size = 2
output_size = 2
X = np.array([[1, 1, 1], [1, -1, -1]])
y = np.array([[1, 1], [-1, -1]])

V = np.array([
    [0.22, 0.57],
    [0.7, 0.21],
    [0.18, 0.11],
    [0.38, 0.44]
])

W = np.array([
    [0.09, 0.81],
    [0.77, 0.86],
    [0.17, 0.29]
])

hidden_act = activation_func.bipolar_sigmoid
de_hidden_act = activation_func.d_bipolar_sigmoid
output_act = activation_func.bipolar_sigmoid
de_output_act = activation_func.d_bipolar_sigmoid
mlp = MLP(
    input_size,
    hidden_size,
    output_size,
    activation_func_hidden=hidden_act,
    activation_func_output=output_act,
    derivative_act_hidden=de_hidden_act,
    derivative_act_output=de_output_act,
    batch_mode=False,
    bias=True,
    print_steps=True,
    init_weights=(W, V)
)
v, w = mlp.train(X, y, epochs=1, learning_rate=0.2)

epoch 1
[[1. 1. 1. 1.]]


ValueError: shapes (1,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)